import 'package:objectbox/objectbox.dart';

/// ObjectBox entity for storing connected Bluetooth FF1 devices.
///
/// This entity persists device information across app sessions, including:
/// - Device identification (deviceId, remoteId)
/// - Device metadata (name, branchName)
/// - Cloud connectivity (topicId)
/// - Connection states and timestamps
@Entity()
class FF1BluetoothDeviceEntity {
  /// Primary key, auto-generated by ObjectBox
  @Id()
  int id = 0;

  /// Unique device identifier (shown on FF1 screen) - used as logical key
  String deviceId;

  /// Bluetooth remote ID (MAC address or UUID depending on platform)
  String remoteId;

  /// User-friendly name for the device
  String name;

  /// Topic ID for cloud/WebSocket communication (obtained after WiFi setup)
  /// Can be empty if not yet connected to WiFi
  String topicId = '';

  /// Release branch (release, demo, qemu, etc.)
  String branchName = 'release';

  /// Timestamp when device was first added (microseconds)
  int createdAtUs;

  /// Timestamp of last update (microseconds)
  int updatedAtUs;

  /// Whether this device is currently the active/casting device
  bool isActive = false;

  /// Connection state: 0 = disconnected, 1 = connected, 2 = connecting
  int connectionState = 0; // 0 = disconnected

  /// Timestamp of last connection attempt (microseconds)
  int lastConnectionAttemptUs = 0;

  /// Number of failed connection attempts
  int failedConnectionAttempts = 0;

  /// Additional metadata stored as JSON
  /// Can be extended to store other device-specific information
  String metadataJson = '{}';

  FF1BluetoothDeviceEntity({
    required this.deviceId,
    required this.remoteId,
    required this.name,
    this.topicId = '',
    this.branchName = 'release',
    required this.createdAtUs,
    required this.updatedAtUs,
    this.isActive = false,
    this.connectionState = 0,
    this.lastConnectionAttemptUs = 0,
    this.failedConnectionAttempts = 0,
    this.metadataJson = '{}',
  });

  /// Create a copy with some fields updated
  FF1BluetoothDeviceEntity copyWith({
    String? deviceId,
    String? remoteId,
    String? name,
    String? topicId,
    String? branchName,
    int? createdAtUs,
    int? updatedAtUs,
    bool? isActive,
    int? connectionState,
    int? lastConnectionAttemptUs,
    int? failedConnectionAttempts,
    String? metadataJson,
  }) {
    return FF1BluetoothDeviceEntity(
      deviceId: deviceId ?? this.deviceId,
      remoteId: remoteId ?? this.remoteId,
      name: name ?? this.name,
      topicId: topicId ?? this.topicId,
      branchName: branchName ?? this.branchName,
      createdAtUs: createdAtUs ?? this.createdAtUs,
      updatedAtUs: updatedAtUs ?? this.updatedAtUs,
      isActive: isActive ?? this.isActive,
      connectionState: connectionState ?? this.connectionState,
      lastConnectionAttemptUs:
          lastConnectionAttemptUs ?? this.lastConnectionAttemptUs,
      failedConnectionAttempts:
          failedConnectionAttempts ?? this.failedConnectionAttempts,
      metadataJson: metadataJson ?? this.metadataJson,
    )..id = id;
  }
}

/// ObjectBox entity for caching remote app config payload and ETag.
///
/// A single row (scope=`app`) is used as the source for local-first startup.
@Entity()
class RemoteAppConfigEntity {
  /// Primary key, auto-generated by ObjectBox.
  @Id()
  int id = 0;

  /// Logical key for singleton storage.
  @Unique()
  String scope;

  /// Last known ETag from the remote config endpoint.
  String etag;

  /// Curated channel URLs in configured order, serialized as JSON string array.
  String curatedChannelUrlsJson;

  /// Feed cache duration in seconds from remote config.
  int feedCacheDurationSec;

  /// Feed content last-updated timestamp (microseconds UTC).
  int feedLastUpdatedAtUs;

  /// Last successful update timestamp (microseconds).
  int updatedAtUs;

  RemoteAppConfigEntity({
    this.scope = 'app',
    this.etag = '',
    this.curatedChannelUrlsJson = '[]',
    this.feedCacheDurationSec = 0,
    this.feedLastUpdatedAtUs = 0,
    required this.updatedAtUs,
  });
}
