// Reason: ObjectBox model style is schema-driven and intentionally flat.
// ignore_for_file: public_member_api_docs
// ignore_for_file: sort_constructors_first
// ignore_for_file: always_put_required_named_parameters_first

import 'package:objectbox/objectbox.dart';

/// ObjectBox entity for storing connected Bluetooth FF1 devices.
///
/// This entity persists device information across app sessions, including:
/// - Device identification (deviceId, remoteId)
/// - Device metadata (name, branchName)
/// - Cloud connectivity (topicId)
/// - Connection states and timestamps
@Entity()
class FF1BluetoothDeviceEntity {
  /// Primary key, auto-generated by ObjectBox
  @Id()
  int id = 0;

  /// Unique device identifier (shown on FF1 screen) - used as logical key
  String deviceId;

  /// Bluetooth remote ID (MAC address or UUID depending on platform)
  String remoteId;

  /// User-friendly name for the device
  String name;

  /// Topic ID for cloud/WebSocket communication (obtained after WiFi setup)
  /// Can be empty if not yet connected to WiFi
  String topicId = '';

  /// Release branch (release, demo, qemu, etc.)
  String branchName = 'release';

  /// Timestamp when device was first added (microseconds)
  int createdAtUs;

  /// Timestamp of last update (microseconds)
  int updatedAtUs;

  /// Whether this device is currently the active/casting device
  bool isActive = false;

  /// Connection state: 0 = disconnected, 1 = connected, 2 = connecting
  int connectionState = 0; // 0 = disconnected

  /// Timestamp of last connection attempt (microseconds)
  int lastConnectionAttemptUs = 0;

  /// Number of failed connection attempts
  int failedConnectionAttempts = 0;

  /// Additional metadata stored as JSON
  /// Can be extended to store other device-specific information
  String metadataJson = '{}';

  FF1BluetoothDeviceEntity({
    required this.deviceId,
    required this.remoteId,
    required this.name,
    this.topicId = '',
    this.branchName = 'release',
    required this.createdAtUs,
    required this.updatedAtUs,
    this.isActive = false,
    this.connectionState = 0,
    this.lastConnectionAttemptUs = 0,
    this.failedConnectionAttempts = 0,
    this.metadataJson = '{}',
  });

  /// Create a copy with some fields updated
  FF1BluetoothDeviceEntity copyWith({
    String? deviceId,
    String? remoteId,
    String? name,
    String? topicId,
    String? branchName,
    int? createdAtUs,
    int? updatedAtUs,
    bool? isActive,
    int? connectionState,
    int? lastConnectionAttemptUs,
    int? failedConnectionAttempts,
    String? metadataJson,
  }) {
    return FF1BluetoothDeviceEntity(
      deviceId: deviceId ?? this.deviceId,
      remoteId: remoteId ?? this.remoteId,
      name: name ?? this.name,
      topicId: topicId ?? this.topicId,
      branchName: branchName ?? this.branchName,
      createdAtUs: createdAtUs ?? this.createdAtUs,
      updatedAtUs: updatedAtUs ?? this.updatedAtUs,
      isActive: isActive ?? this.isActive,
      connectionState: connectionState ?? this.connectionState,
      lastConnectionAttemptUs:
          lastConnectionAttemptUs ?? this.lastConnectionAttemptUs,
      failedConnectionAttempts:
          failedConnectionAttempts ?? this.failedConnectionAttempts,
      metadataJson: metadataJson ?? this.metadataJson,
    )..id = id;
  }
}

/// ObjectBox entity for caching remote app config payload and ETag.
///
/// A single row (scope=`app`) is used as the source for local-first startup.
@Entity()
class RemoteAppConfigEntity {
  /// Primary key, auto-generated by ObjectBox.
  @Id()
  int id = 0;

  /// Logical key for singleton storage.
  @Unique()
  String scope;

  /// Last known ETag from the remote config endpoint.
  String etag;

  /// Cached publishers payload serialized as JSON.
  String curatedChannelUrlsJson;

  /// Feed cache duration in seconds from remote config.
  int feedCacheDurationSec;

  /// Feed content last-updated timestamp (microseconds UTC).
  int feedLastUpdatedAtUs;

  /// Last successful update timestamp (microseconds).
  int updatedAtUs;

  RemoteAppConfigEntity({
    this.scope = 'app',
    this.etag = '',
    this.curatedChannelUrlsJson = '[]',
    this.feedCacheDurationSec = 0,
    this.feedLastUpdatedAtUs = 0,
    required this.updatedAtUs,
  });
}

/// Singleton non-SQLite app state.
///
/// Purpose: store global flags/config that are not represented by SQLite data.
@Entity()
class AppStateEntity {
  /// Primary key, auto-generated by ObjectBox.
  @Id()
  int id = 0;

  /// Singleton scope key.
  @Unique()
  String scope;

  /// Global epoch used to force all feed endpoints stale.
  ///
  /// Usage: when > 0, feed refresh checks use this timestamp instead of
  /// per-feed timestamps.
  int globalLastRefreshEpochUs;

  /// Feed cache time-to-live in seconds.
  ///
  /// Usage: compared against per-feed last refresh timestamps.
  int feedCacheDurationSeconds;

  /// Feed content last-updated timestamp from remote config.
  ///
  /// Usage: if newer than per-feed refresh timestamp, feed should reload.
  int feedLastUpdatedAtUs;

  /// Onboarding completion flag.
  bool hasSeenOnboarding;

  /// One-time tooltip completion flag for Play-to-FF1 affordance.
  bool hasSeenPlayToFf1Tooltip;

  /// Last write timestamp for this singleton state.
  int updatedAtUs;

  AppStateEntity({
    this.scope = 'app',
    this.globalLastRefreshEpochUs = 0,
    this.feedCacheDurationSeconds = 86400,
    this.feedLastUpdatedAtUs = 1672531200000000,
    this.hasSeenOnboarding = false,
    this.hasSeenPlayToFf1Tooltip = false,
    required this.updatedAtUs,
  });
}

/// Per-address/pseudo-address state row.
///
/// Purpose: store minimal incremental sync cursor and indexing process status.
/// Address playlists themselves remain in SQLite.
@Entity()
class AppStateAddressEntity {
  /// Primary key, auto-generated by ObjectBox.
  @Id()
  int id = 0;

  /// Unique key for row.
  ///
  /// Usage:
  /// - Uppercased wallet address for address-related state.
  /// - `FEED::<baseUrl>` for per-feed refresh timestamp rows.
  @Unique()
  String normalizedAddress;

  /// Feed endpoint represented by this row when key is `FEED::<baseUrl>`.
  /// Empty for address rows.
  String feedBaseUrl;

  /// Last refresh timestamp for [feedBaseUrl].
  int feedLastRefreshAtUs;

  /// Whether [indexerAnchor] is set.
  bool hasIndexerAnchor;

  /// Incremental indexer anchor cursor per address.
  int indexerAnchor;

  /// Indexing process state enum ordinal.
  int indexingProcessStateIndex;

  /// Last indexing process update timestamp.
  int indexingProcessUpdatedAtUs;

  /// Error details for indexing process state transitions.
  String indexingProcessErrorMessage;

  /// Last write timestamp for this row.
  int updatedAtUs;

  AppStateAddressEntity({
    required this.normalizedAddress,
    this.feedBaseUrl = '',
    this.feedLastRefreshAtUs = 0,
    this.hasIndexerAnchor = false,
    this.indexerAnchor = 0,
    this.indexingProcessStateIndex = 0,
    this.indexingProcessUpdatedAtUs = 0,
    this.indexingProcessErrorMessage = '',
    required this.updatedAtUs,
  });
}

/// Persisted checkpoint/state for background workers.
///
/// Each worker uses one row keyed by [workerId]. Checkpoint payload is stored
/// as JSON to keep worker-specific progress minimal and versionable.
@Entity()
class WorkerStateEntity {
  /// Primary key, auto-generated by ObjectBox.
  @Id()
  int id = 0;

  /// Stable worker identifier.
  @Unique()
  String workerId;

  /// Persisted worker lifecycle state enum ordinal.
  int stateIndex;

  /// Whether [checkpointJson] should be considered during restore.
  bool hasCheckpoint;

  /// Worker-specific checkpoint payload encoded as JSON object string.
  String checkpointJson;

  /// Last write timestamp (microseconds UTC).
  int updatedAtUs;

  WorkerStateEntity({
    required this.workerId,
    this.stateIndex = 0,
    this.hasCheckpoint = false,
    this.checkpointJson = '{}',
    required this.updatedAtUs,
  });
}
