// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'infra/database/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2853626907365117643),
    name: 'FF1BluetoothDeviceEntity',
    lastPropertyId: const obx_int.IdUid(13, 8737347528951916824),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8217879004984645775),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6048094844959998607),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4976057546862378122),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1518878938718945078),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8170522507265156275),
        name: 'topicId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6196593455555021706),
        name: 'branchName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4760008805664162387),
        name: 'createdAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1644365094948404863),
        name: 'updatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7253589737666510649),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7653660604562504774),
        name: 'connectionState',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6871174439474867832),
        name: 'lastConnectionAttemptUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7901243151262088886),
        name: 'failedConnectionAttempts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8737347528951916824),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2853626907365117643),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FF1BluetoothDeviceEntity:
        obx_int.EntityDefinition<FF1BluetoothDeviceEntity>(
          model: _entities[0],
          toOneRelations: (FF1BluetoothDeviceEntity object) => [],
          toManyRelations: (FF1BluetoothDeviceEntity object) => {},
          getId: (FF1BluetoothDeviceEntity object) => object.id,
          setId: (FF1BluetoothDeviceEntity object, int id) {
            object.id = id;
          },
          objectToFB: (FF1BluetoothDeviceEntity object, fb.Builder fbb) {
            final deviceIdOffset = fbb.writeString(object.deviceId);
            final remoteIdOffset = fbb.writeString(object.remoteId);
            final nameOffset = fbb.writeString(object.name);
            final topicIdOffset = fbb.writeString(object.topicId);
            final branchNameOffset = fbb.writeString(object.branchName);
            final metadataJsonOffset = fbb.writeString(object.metadataJson);
            fbb.startTable(14);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, deviceIdOffset);
            fbb.addOffset(2, remoteIdOffset);
            fbb.addOffset(3, nameOffset);
            fbb.addOffset(4, topicIdOffset);
            fbb.addOffset(5, branchNameOffset);
            fbb.addInt64(6, object.createdAtUs);
            fbb.addInt64(7, object.updatedAtUs);
            fbb.addBool(8, object.isActive);
            fbb.addInt64(9, object.connectionState);
            fbb.addInt64(10, object.lastConnectionAttemptUs);
            fbb.addInt64(11, object.failedConnectionAttempts);
            fbb.addOffset(12, metadataJsonOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final deviceIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final remoteIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final topicIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final branchNameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final createdAtUsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              16,
              0,
            );
            final updatedAtUsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final isActiveParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              20,
              false,
            );
            final connectionStateParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              22,
              0,
            );
            final lastConnectionAttemptUsParam = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 24, 0);
            final failedConnectionAttemptsParam = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 26, 0);
            final metadataJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 28, '');
            final object = FF1BluetoothDeviceEntity(
              deviceId: deviceIdParam,
              remoteId: remoteIdParam,
              name: nameParam,
              topicId: topicIdParam,
              branchName: branchNameParam,
              createdAtUs: createdAtUsParam,
              updatedAtUs: updatedAtUsParam,
              isActive: isActiveParam,
              connectionState: connectionStateParam,
              lastConnectionAttemptUs: lastConnectionAttemptUsParam,
              failedConnectionAttempts: failedConnectionAttemptsParam,
              metadataJson: metadataJsonParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FF1BluetoothDeviceEntity] entity fields to define ObjectBox queries.
class FF1BluetoothDeviceEntity_ {
  /// See [FF1BluetoothDeviceEntity.id].
  static final id = obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[0],
  );

  /// See [FF1BluetoothDeviceEntity.deviceId].
  static final deviceId = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[1],
  );

  /// See [FF1BluetoothDeviceEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[2],
  );

  /// See [FF1BluetoothDeviceEntity.name].
  static final name = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[3],
  );

  /// See [FF1BluetoothDeviceEntity.topicId].
  static final topicId = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[4],
  );

  /// See [FF1BluetoothDeviceEntity.branchName].
  static final branchName = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[5],
  );

  /// See [FF1BluetoothDeviceEntity.createdAtUs].
  static final createdAtUs = obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[6],
  );

  /// See [FF1BluetoothDeviceEntity.updatedAtUs].
  static final updatedAtUs = obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[7],
  );

  /// See [FF1BluetoothDeviceEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[8],
  );

  /// See [FF1BluetoothDeviceEntity.connectionState].
  static final connectionState =
      obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
        _entities[0].properties[9],
      );

  /// See [FF1BluetoothDeviceEntity.lastConnectionAttemptUs].
  static final lastConnectionAttemptUs =
      obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
        _entities[0].properties[10],
      );

  /// See [FF1BluetoothDeviceEntity.failedConnectionAttempts].
  static final failedConnectionAttempts =
      obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
        _entities[0].properties[11],
      );

  /// See [FF1BluetoothDeviceEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[12],
  );
}
