// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'infra/database/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2853626907365117643),
    name: 'FF1BluetoothDeviceEntity',
    lastPropertyId: const obx_int.IdUid(13, 8737347528951916824),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8217879004984645775),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6048094844959998607),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4976057546862378122),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1518878938718945078),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8170522507265156275),
        name: 'topicId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6196593455555021706),
        name: 'branchName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4760008805664162387),
        name: 'createdAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1644365094948404863),
        name: 'updatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7253589737666510649),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7653660604562504774),
        name: 'connectionState',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6871174439474867832),
        name: 'lastConnectionAttemptUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7901243151262088886),
        name: 'failedConnectionAttempts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8737347528951916824),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7506149401476678293),
    name: 'RemoteAppConfigEntity',
    lastPropertyId: const obx_int.IdUid(12, 7038997176806896091),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7086625386443446574),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9083997618836770667),
        name: 'scope',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1584066664369836598),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9049828629891282188),
        name: 'etag',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 524985703992515482),
        name: 'updatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6931567675333886946),
        name: 'curatedChannelUrlsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2827048657705408854),
        name: 'feedCacheDurationSec',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7038997176806896091),
        name: 'feedLastUpdatedAtUs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 3855157679464200367),
    name: 'AppStateAddressEntity',
    lastPropertyId: const obx_int.IdUid(15, 3445134738243097972),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 317635060939298668),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8540314580923552008),
        name: 'normalizedAddress',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 3962431394130676537),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7031346450320634061),
        name: 'hasIndexerAnchor',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6219212707173673109),
        name: 'indexerAnchor',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 385594094139718018),
        name: 'indexingProcessStateIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 545011976724115932),
        name: 'indexingProcessUpdatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3546671632087074484),
        name: 'indexingProcessErrorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7205756033359539431),
        name: 'updatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3764280306253148323),
        name: 'indexingProcessWorkflowId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 4993529541343759207),
    name: 'AppStateEntity',
    lastPropertyId: const obx_int.IdUid(10, 846777149020970588),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1602266074075108982),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 323185854255679874),
        name: 'scope',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(10, 732558272281661289),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 123103053460371747),
        name: 'globalLastRefreshEpochUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3918002085832926755),
        name: 'feedCacheDurationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4649454171216932893),
        name: 'feedLastUpdatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8901278758853666615),
        name: 'hasSeenOnboarding',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5911033282435046743),
        name: 'hasSeenPlayToFf1Tooltip',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7087934475054438830),
        name: 'updatedAtUs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5874727476430855017),
        name: 'isMigrated',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 846777149020970588),
        name: 'hasCompletedSeedDownload',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 2953628364725163367),
    name: 'TrackedAddressEntity',
    lastPropertyId: const obx_int.IdUid(4, 3266366044635203300),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8240218798167199216),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6582619908301915819),
        name: 'normalizedAddress',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(12, 6965894134390285096),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3236910916000618783),
        name: 'alias',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3266366044635203300),
        name: 'createdAtUs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(13, 2953628364725163367),
    lastIndexId: const obx_int.IdUid(12, 6965894134390285096),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      770798788842803181,
      621262666537860215,
      2376011165647591893,
      1429740381634624119,
      841839052629614674,
      8091506624394555565,
      7348313918501083823,
      8386579186992898493,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4548421187535112785,
      8241133500042741809,
      1779253016339897687,
      5381724396762660670,
      6726641447328928585,
      3632903845183718328,
      3009418160042647579,
      6534045840994551284,
      3449299448078010116,
      9155238587819792449,
      1275414877543981756,
      2750324100786103253,
      6939807587511420123,
      6445565942409530247,
      8024654198762068213,
      1704777368388386572,
      6560765894971238813,
      8549789255814813415,
      8886576963508854418,
      6889840676891888330,
      5383483374386539172,
      5959801751768331508,
      5330089767041571057,
      7285359236783854916,
      3078368582325569633,
      4031444646087664739,
      1652990674434451850,
      2256204518459881189,
      6593212252882292596,
      3419678040034350389,
      7217055167862178741,
      103208206535744154,
      2910467538557961849,
      8474997703388986960,
      9024476539497481816,
      7026421341565984040,
      7806560449660627472,
      8634257928218582145,
      8352808654578695977,
      5237487681711859762,
      5058690585758162742,
      8175324511364461655,
      3445134738243097972,
      8877341932018307913,
      1404419168567981741,
      671751466930742228,
      3462060407990166466,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FF1BluetoothDeviceEntity:
        obx_int.EntityDefinition<FF1BluetoothDeviceEntity>(
          model: _entities[0],
          toOneRelations: (FF1BluetoothDeviceEntity object) => [],
          toManyRelations: (FF1BluetoothDeviceEntity object) => {},
          getId: (FF1BluetoothDeviceEntity object) => object.id,
          setId: (FF1BluetoothDeviceEntity object, int id) {
            object.id = id;
          },
          objectToFB: (FF1BluetoothDeviceEntity object, fb.Builder fbb) {
            final deviceIdOffset = fbb.writeString(object.deviceId);
            final remoteIdOffset = fbb.writeString(object.remoteId);
            final nameOffset = fbb.writeString(object.name);
            final topicIdOffset = fbb.writeString(object.topicId);
            final branchNameOffset = fbb.writeString(object.branchName);
            final metadataJsonOffset = fbb.writeString(object.metadataJson);
            fbb.startTable(14);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, deviceIdOffset);
            fbb.addOffset(2, remoteIdOffset);
            fbb.addOffset(3, nameOffset);
            fbb.addOffset(4, topicIdOffset);
            fbb.addOffset(5, branchNameOffset);
            fbb.addInt64(6, object.createdAtUs);
            fbb.addInt64(7, object.updatedAtUs);
            fbb.addBool(8, object.isActive);
            fbb.addInt64(9, object.connectionState);
            fbb.addInt64(10, object.lastConnectionAttemptUs);
            fbb.addInt64(11, object.failedConnectionAttempts);
            fbb.addOffset(12, metadataJsonOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final deviceIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final remoteIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final topicIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final branchNameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final createdAtUsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              16,
              0,
            );
            final updatedAtUsParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              18,
              0,
            );
            final isActiveParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              20,
              false,
            );
            final connectionStateParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              22,
              0,
            );
            final lastConnectionAttemptUsParam = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 24, 0);
            final failedConnectionAttemptsParam = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 26, 0);
            final metadataJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 28, '');
            final object = FF1BluetoothDeviceEntity(
              deviceId: deviceIdParam,
              remoteId: remoteIdParam,
              name: nameParam,
              topicId: topicIdParam,
              branchName: branchNameParam,
              createdAtUs: createdAtUsParam,
              updatedAtUs: updatedAtUsParam,
              isActive: isActiveParam,
              connectionState: connectionStateParam,
              lastConnectionAttemptUs: lastConnectionAttemptUsParam,
              failedConnectionAttempts: failedConnectionAttemptsParam,
              metadataJson: metadataJsonParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
    RemoteAppConfigEntity: obx_int.EntityDefinition<RemoteAppConfigEntity>(
      model: _entities[1],
      toOneRelations: (RemoteAppConfigEntity object) => [],
      toManyRelations: (RemoteAppConfigEntity object) => {},
      getId: (RemoteAppConfigEntity object) => object.id,
      setId: (RemoteAppConfigEntity object, int id) {
        object.id = id;
      },
      objectToFB: (RemoteAppConfigEntity object, fb.Builder fbb) {
        final scopeOffset = fbb.writeString(object.scope);
        final etagOffset = fbb.writeString(object.etag);
        final curatedChannelUrlsJsonOffset = fbb.writeString(
          object.curatedChannelUrlsJson,
        );
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, scopeOffset);
        fbb.addOffset(2, etagOffset);
        fbb.addInt64(4, object.updatedAtUs);
        fbb.addOffset(5, curatedChannelUrlsJsonOffset);
        fbb.addInt64(10, object.feedCacheDurationSec);
        fbb.addInt64(11, object.feedLastUpdatedAtUs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final scopeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final etagParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final curatedChannelUrlsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final feedCacheDurationSecParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final feedLastUpdatedAtUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final updatedAtUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = RemoteAppConfigEntity(
          scope: scopeParam,
          etag: etagParam,
          curatedChannelUrlsJson: curatedChannelUrlsJsonParam,
          feedCacheDurationSec: feedCacheDurationSecParam,
          feedLastUpdatedAtUs: feedLastUpdatedAtUsParam,
          updatedAtUs: updatedAtUsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    AppStateAddressEntity: obx_int.EntityDefinition<AppStateAddressEntity>(
      model: _entities[2],
      toOneRelations: (AppStateAddressEntity object) => [],
      toManyRelations: (AppStateAddressEntity object) => {},
      getId: (AppStateAddressEntity object) => object.id,
      setId: (AppStateAddressEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppStateAddressEntity object, fb.Builder fbb) {
        final normalizedAddressOffset = fbb.writeString(
          object.normalizedAddress,
        );
        final indexingProcessErrorMessageOffset = fbb.writeString(
          object.indexingProcessErrorMessage,
        );
        final indexingProcessWorkflowIdOffset = fbb.writeString(
          object.indexingProcessWorkflowId,
        );
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, normalizedAddressOffset);
        fbb.addBool(4, object.hasIndexerAnchor);
        fbb.addInt64(5, object.indexerAnchor);
        fbb.addInt64(6, object.indexingProcessStateIndex);
        fbb.addInt64(7, object.indexingProcessUpdatedAtUs);
        fbb.addOffset(8, indexingProcessErrorMessageOffset);
        fbb.addInt64(9, object.updatedAtUs);
        fbb.addOffset(12, indexingProcessWorkflowIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final normalizedAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final hasIndexerAnchorParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final indexerAnchorParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final indexingProcessStateIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final indexingProcessUpdatedAtUsParam = const fb.Int64Reader()
            .vTableGet(buffer, rootOffset, 18, 0);
        final indexingProcessErrorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final indexingProcessWorkflowIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final updatedAtUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final object = AppStateAddressEntity(
          normalizedAddress: normalizedAddressParam,
          hasIndexerAnchor: hasIndexerAnchorParam,
          indexerAnchor: indexerAnchorParam,
          indexingProcessStateIndex: indexingProcessStateIndexParam,
          indexingProcessUpdatedAtUs: indexingProcessUpdatedAtUsParam,
          indexingProcessErrorMessage: indexingProcessErrorMessageParam,
          indexingProcessWorkflowId: indexingProcessWorkflowIdParam,
          updatedAtUs: updatedAtUsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    AppStateEntity: obx_int.EntityDefinition<AppStateEntity>(
      model: _entities[3],
      toOneRelations: (AppStateEntity object) => [],
      toManyRelations: (AppStateEntity object) => {},
      getId: (AppStateEntity object) => object.id,
      setId: (AppStateEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppStateEntity object, fb.Builder fbb) {
        final scopeOffset = fbb.writeString(object.scope);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, scopeOffset);
        fbb.addInt64(2, object.globalLastRefreshEpochUs);
        fbb.addInt64(3, object.feedCacheDurationSeconds);
        fbb.addInt64(4, object.feedLastUpdatedAtUs);
        fbb.addBool(5, object.hasSeenOnboarding);
        fbb.addBool(6, object.hasSeenPlayToFf1Tooltip);
        fbb.addInt64(7, object.updatedAtUs);
        fbb.addBool(8, object.isMigrated);
        fbb.addBool(9, object.hasCompletedSeedDownload);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final scopeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final globalLastRefreshEpochUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final feedCacheDurationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final feedLastUpdatedAtUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final hasSeenOnboardingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final hasSeenPlayToFf1TooltipParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final isMigratedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final hasCompletedSeedDownloadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final updatedAtUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = AppStateEntity(
          scope: scopeParam,
          globalLastRefreshEpochUs: globalLastRefreshEpochUsParam,
          feedCacheDurationSeconds: feedCacheDurationSecondsParam,
          feedLastUpdatedAtUs: feedLastUpdatedAtUsParam,
          hasSeenOnboarding: hasSeenOnboardingParam,
          hasSeenPlayToFf1Tooltip: hasSeenPlayToFf1TooltipParam,
          isMigrated: isMigratedParam,
          hasCompletedSeedDownload: hasCompletedSeedDownloadParam,
          updatedAtUs: updatedAtUsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    TrackedAddressEntity: obx_int.EntityDefinition<TrackedAddressEntity>(
      model: _entities[4],
      toOneRelations: (TrackedAddressEntity object) => [],
      toManyRelations: (TrackedAddressEntity object) => {},
      getId: (TrackedAddressEntity object) => object.id,
      setId: (TrackedAddressEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TrackedAddressEntity object, fb.Builder fbb) {
        final normalizedAddressOffset = fbb.writeString(
          object.normalizedAddress,
        );
        final aliasOffset = fbb.writeString(object.alias);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, normalizedAddressOffset);
        fbb.addOffset(2, aliasOffset);
        fbb.addInt64(3, object.createdAtUs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final normalizedAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final aliasParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtUsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = TrackedAddressEntity(
          normalizedAddress: normalizedAddressParam,
          alias: aliasParam,
          createdAtUs: createdAtUsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FF1BluetoothDeviceEntity] entity fields to define ObjectBox queries.
class FF1BluetoothDeviceEntity_ {
  /// See [FF1BluetoothDeviceEntity.id].
  static final id = obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[0],
  );

  /// See [FF1BluetoothDeviceEntity.deviceId].
  static final deviceId = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[1],
  );

  /// See [FF1BluetoothDeviceEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[2],
  );

  /// See [FF1BluetoothDeviceEntity.name].
  static final name = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[3],
  );

  /// See [FF1BluetoothDeviceEntity.topicId].
  static final topicId = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[4],
  );

  /// See [FF1BluetoothDeviceEntity.branchName].
  static final branchName = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[5],
  );

  /// See [FF1BluetoothDeviceEntity.createdAtUs].
  static final createdAtUs = obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[6],
  );

  /// See [FF1BluetoothDeviceEntity.updatedAtUs].
  static final updatedAtUs = obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[7],
  );

  /// See [FF1BluetoothDeviceEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[8],
  );

  /// See [FF1BluetoothDeviceEntity.connectionState].
  static final connectionState =
      obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
        _entities[0].properties[9],
      );

  /// See [FF1BluetoothDeviceEntity.lastConnectionAttemptUs].
  static final lastConnectionAttemptUs =
      obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
        _entities[0].properties[10],
      );

  /// See [FF1BluetoothDeviceEntity.failedConnectionAttempts].
  static final failedConnectionAttempts =
      obx.QueryIntegerProperty<FF1BluetoothDeviceEntity>(
        _entities[0].properties[11],
      );

  /// See [FF1BluetoothDeviceEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<FF1BluetoothDeviceEntity>(
    _entities[0].properties[12],
  );
}

/// [RemoteAppConfigEntity] entity fields to define ObjectBox queries.
class RemoteAppConfigEntity_ {
  /// See [RemoteAppConfigEntity.id].
  static final id = obx.QueryIntegerProperty<RemoteAppConfigEntity>(
    _entities[1].properties[0],
  );

  /// See [RemoteAppConfigEntity.scope].
  static final scope = obx.QueryStringProperty<RemoteAppConfigEntity>(
    _entities[1].properties[1],
  );

  /// See [RemoteAppConfigEntity.etag].
  static final etag = obx.QueryStringProperty<RemoteAppConfigEntity>(
    _entities[1].properties[2],
  );

  /// See [RemoteAppConfigEntity.updatedAtUs].
  static final updatedAtUs = obx.QueryIntegerProperty<RemoteAppConfigEntity>(
    _entities[1].properties[3],
  );

  /// See [RemoteAppConfigEntity.curatedChannelUrlsJson].
  static final curatedChannelUrlsJson =
      obx.QueryStringProperty<RemoteAppConfigEntity>(
        _entities[1].properties[4],
      );

  /// See [RemoteAppConfigEntity.feedCacheDurationSec].
  static final feedCacheDurationSec =
      obx.QueryIntegerProperty<RemoteAppConfigEntity>(
        _entities[1].properties[5],
      );

  /// See [RemoteAppConfigEntity.feedLastUpdatedAtUs].
  static final feedLastUpdatedAtUs =
      obx.QueryIntegerProperty<RemoteAppConfigEntity>(
        _entities[1].properties[6],
      );
}

/// [AppStateAddressEntity] entity fields to define ObjectBox queries.
class AppStateAddressEntity_ {
  /// See [AppStateAddressEntity.id].
  static final id = obx.QueryIntegerProperty<AppStateAddressEntity>(
    _entities[2].properties[0],
  );

  /// See [AppStateAddressEntity.normalizedAddress].
  static final normalizedAddress =
      obx.QueryStringProperty<AppStateAddressEntity>(
        _entities[2].properties[1],
      );

  /// See [AppStateAddressEntity.hasIndexerAnchor].
  static final hasIndexerAnchor =
      obx.QueryBooleanProperty<AppStateAddressEntity>(
        _entities[2].properties[2],
      );

  /// See [AppStateAddressEntity.indexerAnchor].
  static final indexerAnchor = obx.QueryIntegerProperty<AppStateAddressEntity>(
    _entities[2].properties[3],
  );

  /// See [AppStateAddressEntity.indexingProcessStateIndex].
  static final indexingProcessStateIndex =
      obx.QueryIntegerProperty<AppStateAddressEntity>(
        _entities[2].properties[4],
      );

  /// See [AppStateAddressEntity.indexingProcessUpdatedAtUs].
  static final indexingProcessUpdatedAtUs =
      obx.QueryIntegerProperty<AppStateAddressEntity>(
        _entities[2].properties[5],
      );

  /// See [AppStateAddressEntity.indexingProcessErrorMessage].
  static final indexingProcessErrorMessage =
      obx.QueryStringProperty<AppStateAddressEntity>(
        _entities[2].properties[6],
      );

  /// See [AppStateAddressEntity.updatedAtUs].
  static final updatedAtUs = obx.QueryIntegerProperty<AppStateAddressEntity>(
    _entities[2].properties[7],
  );

  /// See [AppStateAddressEntity.indexingProcessWorkflowId].
  static final indexingProcessWorkflowId =
      obx.QueryStringProperty<AppStateAddressEntity>(
        _entities[2].properties[8],
      );
}

/// [AppStateEntity] entity fields to define ObjectBox queries.
class AppStateEntity_ {
  /// See [AppStateEntity.id].
  static final id = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[3].properties[0],
  );

  /// See [AppStateEntity.scope].
  static final scope = obx.QueryStringProperty<AppStateEntity>(
    _entities[3].properties[1],
  );

  /// See [AppStateEntity.globalLastRefreshEpochUs].
  static final globalLastRefreshEpochUs =
      obx.QueryIntegerProperty<AppStateEntity>(_entities[3].properties[2]);

  /// See [AppStateEntity.feedCacheDurationSeconds].
  static final feedCacheDurationSeconds =
      obx.QueryIntegerProperty<AppStateEntity>(_entities[3].properties[3]);

  /// See [AppStateEntity.feedLastUpdatedAtUs].
  static final feedLastUpdatedAtUs = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[3].properties[4],
  );

  /// See [AppStateEntity.hasSeenOnboarding].
  static final hasSeenOnboarding = obx.QueryBooleanProperty<AppStateEntity>(
    _entities[3].properties[5],
  );

  /// See [AppStateEntity.hasSeenPlayToFf1Tooltip].
  static final hasSeenPlayToFf1Tooltip =
      obx.QueryBooleanProperty<AppStateEntity>(_entities[3].properties[6]);

  /// See [AppStateEntity.updatedAtUs].
  static final updatedAtUs = obx.QueryIntegerProperty<AppStateEntity>(
    _entities[3].properties[7],
  );

  /// See [AppStateEntity.isMigrated].
  static final isMigrated = obx.QueryBooleanProperty<AppStateEntity>(
    _entities[3].properties[8],
  );

  /// See [AppStateEntity.hasCompletedSeedDownload].
  static final hasCompletedSeedDownload =
      obx.QueryBooleanProperty<AppStateEntity>(_entities[3].properties[9]);
}

/// [TrackedAddressEntity] entity fields to define ObjectBox queries.
class TrackedAddressEntity_ {
  /// See [TrackedAddressEntity.id].
  static final id = obx.QueryIntegerProperty<TrackedAddressEntity>(
    _entities[4].properties[0],
  );

  /// See [TrackedAddressEntity.normalizedAddress].
  static final normalizedAddress =
      obx.QueryStringProperty<TrackedAddressEntity>(_entities[4].properties[1]);

  /// See [TrackedAddressEntity.alias].
  static final alias = obx.QueryStringProperty<TrackedAddressEntity>(
    _entities[4].properties[2],
  );

  /// See [TrackedAddressEntity.createdAtUs].
  static final createdAtUs = obx.QueryIntegerProperty<TrackedAddressEntity>(
    _entities[4].properties[3],
  );
}
